build:
  environment:
    pythonVersion: 3.10

services:
  - type: cron
    name: hyrox-monitor
    schedule: "@hourly"
    envVars:
      - key: EMAIL_FROM
        value: oray.gungor@gmail.com
      - key: EMAIL_PASS
        value: angfrslhpwzyfwqx
      - key: EMAIL_TO
        value: oray.gungor@gmail.com
      - key: GH_TOKEN          # GitHub personal-access-token (gist scope)
        sync: false
      - key: GIST_ID           # the hex ID of your private gist
        sync: false
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py



